FROM alpine:3.11 AS qemu
RUN apk --update add --no-cache curl
RUN cd /tmp && \
    curl -L https://github.com/balena-io/qemu/releases/download/v3.0.0%2Bresin/qemu-3.0.0+resin-arm.tar.gz | tar zxvf - -C . && mv qemu-3.0.0+resin-arm/qemu-arm-static .

FROM arm32v6/alpine:3.11
COPY --from=qemu /tmp/qemu-arm-static /usr/bin/
RUN apk --update add --no-cache mosquitto
ENV HOST mqtt
ENV PORT 1883
ENV USER raspi-stats
ENV PASS changeme
ENV TOPIC raspi
WORKDIR /app
ADD run.sh /app
CMD ["/app/run.sh"]
